[package]
name = "wallfolio-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
clap.workspace = true
wallfolio-protocol = { path = "../wallfolio-protocol" }

[[bin]]
name = "wallfolio"
path = "src/main.rs"
