[package]
name = "wallfolio-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
anyhow.workspace = true
serde_json.workspace = true
reqwest.workspace = true
wallfolio-provider-api = { path = "../wallfolio-provider-api" }
wallfolio-backend-api = { path = "../wallfolio-backend-api" }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
